         0         1                           -1 #al layer 1
         0         1                           -1 #al layer 2
         0         1                           -1 #al layer 3
         0         1                           -1 #al layer 4
         0         1                           -1 #al layer 5
         0         1                           -1 #al layer 6
         0         1                           -1 #al layer 7
         0         1                           -1 #al layer 8
         0         1                           -1 #al layer 9
         0         1                           -1 #al layer 10
         0         1                           -1 #al layer 11
         0         1                           -1 #al layer 12
         0         1                           -1 #al layer 13
         0         1                           -1 #al layer 14
         0         1                           -1 #al layer 15
         0         1                           -1 #al layer 16
         0         1                           -1 #al layer 17
         0         1                           -1 #al layer 18
         0         1                           -1 #al layer 19
         0         1                           -1 #al layer 20
         0         1                           -1 #al layer 21
         0         1                           -1 #al layer 22
         0         1                           -1 #al layer 23
         0         1                           -1 #al layer 24
         0         1                           -1 #al layer 25
         0         1                           -1 #al layer 26
         0         1                           -1 #al layer 27
         0         1                           -1 #al layer 28
         0         1                           -1 #al layer 29
         0         1                           -1 #al layer 30
         0         1                           -1 #al layer 31
         0         1                           -1 #al layer 32
         0         1                           -1 #al layer 33
         0         1                           -1 #al layer 34
         0         1                           -1 #al layer 35
         0         1                           -1 #al layer 36
         0         1                           -1 #al layer 37
         0         1                           -1 #al layer 38
         0         1                           -1 #al layer 39
         0         1                           -1 #al layer 40
         0         1                           -1 #al layer 41
         0         1                           -1 #al layer 42
         0         1                           -1 #al layer 43
         0         1                           -1 #al layer 44
         0         1                           -1 #al layer 45
         0         1                           -1 #al layer 46
         0         1                           -1 #al layer 47
         0         1                           -1 #al layer 48
         0         1                           -1 #al layer 49
         0         1                           -1 #al layer 50
         0         1                           -1 #al layer 51
         0         1                           -1 #al layer 52
         0         1                           -1 #al layer 53
         0         1                           -1 #al layer 54
         0         1                           -1 #al layer 55
         0         1                           -1 #al layer 56
         0         1                           -1 #al layer 57
         0         1                           -1 #al layer 58
         0         1                           -1 #al layer 59
         0         1                           -1 #al layer 60
         0         1                           -1 #al layer 61
         0         1                           -1 #al layer 62
         0         1                           -1 #al layer 63
         0         1                           -1 #al layer 64
         0         1                           -1 #al layer 65
         0         1                           -1 #al layer 66
         0         1                           -1 #al layer 67
         0         1                           -1 #al layer 68
         0         1                           -1 #al layer 69
         0         1                           -1 #al layer 70
         0         1                           -1 #al layer 71
         0         1                           -1 #al layer 72
         0         1                           -1 #al layer 73
         0         1                           -1 #al layer 74
         0         1                           -1 #al layer 75
         0         1                           -1 #al layer 76
         0         1                           -1 #al layer 77
         0         1                           -1 #al layer 78
         0         1                           -1 #al layer 79
         0         1                           -1 #al layer 80
         0         1                           -1 #al layer 81
         0         1                           -1 #al layer 82
         0         1                           -1 #al layer 83
         0         1                           -1 #al layer 84
         0         1                           -1 #al layer 85
         0         1                           -1 #al layer 86
         0         1                           -1 #al layer 87
         0         1                           -1 #al layer 88
         0         1                           -1 #al layer 89
         0         1                           -1 #al layer 90
         0         1                           -1 #al layer 91
         0         1                           -1 #al layer 92
         0         1                           -1 #al layer 93
         0         1                           -1 #al layer 94
         0         1                           -1 #al layer 95
         0         1                           -1 #al layer 96
         0         1                           -1 #al layer 97
         0         1                           -1 #al layer 98
         0         1                           -1 #al layer 99
         0         1                           -1 #al layer 100
         0         1                           -1 #al layer 101
         0         1                           -1 #al layer 102
         0         1                           -1 #al layer 103
         0         1                           -1 #al layer 104
         0         1                           -1 #al layer 105
         0         1                           -1 #al layer 106
         0         1                           -1 #al layer 107
         0         1                           -1 #al layer 108
         0         1                           -1 #al layer 109
         0         1                           -1 #al layer 110
         0         1                           -1 #al layer 111
         0         1                           -1 #al layer 112
         0         1                           -1 #al layer 113
         0         1                           -1 #al layer 114
         0         1                           -1 #al layer 115
         0         1                           -1 #al layer 116
         0         1                           -1 #al layer 117
         0         1                           -1 #al layer 118
         0         1                           -1 #al layer 119
         0         1                           -1 #al layer 120
         0         1                           -1 #al layer 121
         0         1                           -1 #al layer 122
         0         1                           -1 #al layer 123
         0         1                           -1 #al layer 124
         0         1                           -1 #al layer 125
         0         1                           -1 #al layer 126
         0         1                           -1 #al layer 127
         0         1                           -1 #al layer 128
         0         1                           -1 #al layer 129
         0         1                           -1 #al layer 130
         0         1                           -1 #al layer 131
         0         1                           -1 #al layer 132
         0         1                           -1 #al layer 133
         0         1                           -1 #al layer 134
         0         1                           -1 #al layer 135
         0         1                           -1 #al layer 136
         0         1                           -1 #al layer 137
         0         1                           -1 #al layer 138
         0         1                           -1 #al layer 139
         0         1                           -1 #al layer 140
         0         1                           -1 #al layer 141
         0         1                           -1 #al layer 142
         0         1                           -1 #al layer 143
         0         1                           -1 #al layer 144
         0         1                           -1 #al layer 145
         0         1                           -1 #al layer 146
         0         1                           -1 #al layer 147
         0         1                           -1 #al layer 148
         0         1                           -1 #al layer 149
         0         1                           -1 #al layer 150
         0         1                           -1 #al layer 151
         0         1                           -1 #al layer 152
         0         1                           -1 #al layer 153
         0         1                           -1 #al layer 154
         0         1                           -1 #al layer 155
         0         1                           -1 #al layer 156
         0         1                           -1 #al layer 157
         0         1                           -1 #al layer 158
         0         1                           -1 #al layer 159
         0         1                           -1 #al layer 160
         0         1                           -1 #al layer 161
         0         1                           -1 #al layer 162
         0         1                           -1 #al layer 163
         0         1                           -1 #al layer 164
         0         1                           -1 #al layer 165
         0         1                           -1 #al layer 166
         0         1                           -1 #al layer 167
         0         1                           -1 #al layer 168
         0         1                           -1 #al layer 169
         0         1                           -1 #al layer 170
         0         1                           -1 #al layer 171
         0         1                           -1 #al layer 172
         0         1                           -1 #al layer 173
         0         1                           -1 #al layer 174
         0         1                           -1 #al layer 175
         0         1                           -1 #al layer 176
         0         1                           -1 #al layer 177
         0         1                           -1 #al layer 178
         0         1                           -1 #al layer 179
         0         1                           -1 #al layer 180
         0         1                           -1 #al layer 181
         0         1                           -1 #al layer 182
         0         1                           -1 #al layer 183
         0         1                           -1 #al layer 184
         0         1                           -1 #al layer 185
         0         1                           -1 #al layer 186
         0         1                           -1 #al layer 187
         0         1                           -1 #al layer 188
         0         1                           -1 #al layer 189
         0         1                           -1 #al layer 190
         0       0.1                           -1 #trpt
         0       0.1                           -1 #trpv
         0  8.64E-05                           -1 #dmcoef1
